//1.

POST http://localhost:3000/register
Content-Type:application/json

{
    "username":"mahesh",
    "name":"Adam Richard",
    "password":"mahesh_1432",
    "gender":"male",
    "location":"Detroit"
}
###
POST http://localhost:3000/login
Content-Type:application/json 

{
    "username":"mahesh",
    "password":"mahesh_1432"
}
###

//3.
PUT http://localhost:3000/change-password
Content-Type:application/json

{
    "username":"mahesh",
    "oldPassword":"mahesh_1432",
    "newPassword":"mahesh@123"
}